### ISSUE TITLE
MQTT connection issue

### ISSUE THREAD

**Issue by rogierg** [dominikberse/homeassistant-bluetooth-mesh#11]
Hi there,

I'm runnning into MQTT connection issues. Running Mosquitto broker 6.1.3. When starting up I get the following errors in the container:

`INFO:root:Awaiting 1 tasks
DEBUG:root:Spawning task to run messenger...
ERROR:root:Task failed
Traceback (most recent call last):
  File "/opt/hass-ble-mesh/gateway/tools/tasks.py", line 36, in _runner
    await task
  File "/opt/hass-ble-mesh/gateway/mqtt/messenger.py", line 78, in run
    await stack.enter_async_context(self._client)
  File "/usr/local/lib/python3.10/contextlib.py", line 619, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/usr/local/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 565, in __aenter__
    await self.connect()
  File "/usr/local/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 234, in connect
    await self._wait_for(self._connected, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 390, in _wait_for
    return await asyncio.wait_for(fut, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
asyncio_mqtt.error.MqttConnectError: [code:5] The connection was refused.
DEBUG:root:run messenger completed`

In Mosquitto's log the following lines show:
`2022-12-24 10:27:45: New connection from 192.168.42.88:37203 on port 1883.
error: received null username or password for unpwd check`

I have tried with both a Mosquitto local user and a hassio user, also with allow_anonymous same error.

**Comment by rogierg** [comment]
Uh... there's no use of these settings in messenger.py? 😊

` self._client = Client(self._config.require('mqtt.broker'))
  self._topic = config.optional('mqtt.topic', 'mqtt_mesh')`

Ah so apparently that was added recently. Building a new version.

**Comment by rogierg** [comment]
Works (as far as MQTT goes)
